###########
# BASE #
###########
FROM python:3.8.5-slim-buster as base

# install system dependencies
RUN apt-get update \
  && apt-get -y install gcc postgresql \
  && apt-get clean

# upgrade pip and install pipenv
RUN pip install --upgrade pip
RUN pip install pipenv

# install dependencies
COPY Pipfile* ./
RUN pipenv install --system --deploy --ignore-pipfile

###########
# BUILDER #
###########
FROM base as builder

# install dev dependencies
RUN pipenv install --system --deploy --ignore-pipfile --dev

# set work directory
WORKDIR /usr/src/app

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# lint
COPY . /usr/src/app/
RUN flake8 .
RUN black --exclude=migrations .
RUN isort ./**/*.py


#########
# FINAL #
#########
FROM base

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system --group app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# add app
COPY . .

# chown all the files to the app user
RUN chown -R app:app $HOME

# change to the app user
USER app

# run gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker